### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'HIC'

### ISSUE THREAD

**Issue by jamesdalg** [gersteinlab/HiC_spector#1]
Using HiC-spector, I really like the simple interface and how accessible it is from standard formats. In my case, I'm trying to use juicer output (.hic files) to get reproducibility statistics from HiC-spector, but I'm getting a python error. Is it my version of python? I looked through the supplementary information and the paper (https://academic.oup.com/bioinformatics/article/33/14/2199/3078603) and can't find specific information that would lead me to understand the source of this error.

(/data/CCRBioinfo/HiC-spector-env/) bash-4.1$ module show julialang
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   /usr/local/lmod/modulefiles/julialang/0.5.2.lua:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
help([[This module sets up the environment for using XXXX.
]])
whatis("Julia: High level, dynamic language for techincal computing")
whatis("Version: 0.5.2")
prepend_path("PATH","/usr/local/apps/julialang/0.5.2/bin")
load("git")

(/data/CCRBioinfo/HiC-spector-env/) bash-4.1$ python run_reproducibility.py -F hicrep1.hic hicrep2.hic
Traceback (most recent call last):
  File "run_reproducibility.py", line 154, in <module>
    main()
  File "run_reproducibility.py", line 139, in main
    M1, M2=Parse_matrix(sys.argv[2],sys.argv[3])
  File "run_reproducibility.py", line 12, in Parse_matrix
    x,y,z=map(int, line.split())
ValueError: invalid literal for int() with base 10: 'HIC'
(/data/CCRBioinfo/HiC-spector-env/) bash-4.1$ python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import   straw

**Comment by jamesdalg** [comment]
If you need, I can send the HiC files to you.

**Comment by ChengfeiYan** [comment]
Hi,
For the .hic format, the command you should use it:
"python run_reproducibility.py -f hic_file1 hic_file2 chrid resolution"

First, you should use "-F" rather than "-f". Second, you should include the chromosome id and the resolution of the HiC matrix. (Such as "10" for the chrid and "50000" for the resolution)

Hope this helps.
Thanks,
Chengfei Yan

**Comment by jamesdalg** [comment]
ChengfeiYan,
I changed the chrid to "chr8" rather than "8", but it works perfectly now. 

error:
One of the chromosomes wasn't found in the file. Check that the chromosome name matches the genome.

Traceback (most recent call last):
  File "run_reproducibility.py", line 154, in <module>
    main()
  File "run_reproducibility.py", line 142, in main
    M1, M2=Parse_matrix_hic(sys.argv[2],sys.argv[3],sys.argv[4],int(sys.argv[5]))
  File "run_reproducibility.py", line 41, in Parse_matrix_hic
    Table1=straw.straw("NONE",file1, chrn, chrn,"BP",resolution)
  File "/data/CCRBioinfo/dalgleishjl/HiC-spector/straw/python/straw.py", line 471, in straw
    master=list1[0]
TypeError: 'int' object has no attribute '__getitem__'


success after changing '8' to 'chr8':
HiC version:  8
HiC version:  8
size of maps: 293
reproducibility score:  0.198
