### ISSUE TITLE
Eigenvector normalization

### ISSUE THREAD

**Issue by srcoulombe** [gersteinlab/HiC_spector#9]
The paper qualifies the eigenvectors used in computing the distance metric as being 'normalized', but I don't see where nor how that normalization is done in the Python code. My guess is the norm is implied to be the L2 norm so that the distance metric compares pairs of unit-length vectors, but that doesn't seem to be the case in the Python implementation, but that doesn't seem to be the case in the Python implementation.

**Comment by quantum-man** [comment]
It's what you have guessed. I think by default eigsh returns unit
eigenvectors.

**Comment by srcoulombe** [comment]
Yes OK thanks for clarifying
